language: python

notifications:
  email: false

python:
  - '3.7'

before_script:
  - pip install -U -r requirements.txt
  - pip install -U -r test_requirements.txt

script:
  - pytest --cov=curve_fit_gui

after_success:
  - coveralls
